name= input("what is your name")
print (" Nice to meet you",name)
color= input("What is your favorite color")
print (color,"That's a nice color")
food= input("What's your favorite food")
print (food,"Sounds yummy")
question= input("do you have to go")
